### ISSUE TITLE
How to verify kernel version

### ISSUE THREAD

**Issue by switit** [bertofurth/Seagate-Central-Slot-In-v5.x-Kernel#1]
The upgrade with samba and new kernel seemed have gone well. However, there doesn't seem to be an explicit way to verify the new linux kernel version. 
$ uname -r
2.6.35.13-cavm1.whitney-econa.whitney-econa
$ ls -al /boot
lrwxrwxrwx  1 root root   50 Mar  4 10:15 uImage -> uImage-2.6.35.13-cavm1.whitney-econa.whitney-econa

Is there a way to verify the kernel version?

**Comment by bertofurth** [comment]
Hi there,

I think that message means that the original Seagate Central kernel is still in place!

With the new kernel, the output should be something like

$uname -r 
5.14.0-sc
$uname -a
Linux NAS-1 5.14.0-sc #1 SMP Fri Sep 10 09:49:35 AEST 2021 armv6l GNU/Linux

Can you confirm that the new version of Samba is running with the "testparm -V" command?

$testparm -V 
Version 4.14.6

Can you follow the instructions in the README_MANUAL_KERNEL_INSTALLATION.md document at

https://github.com/bertofurth/Seagate-Central-Slot-In-v5.x-Kernel/blob/main/README_MANUAL_KERNEL_INSTALLATION.md

under the sections entitled "Find out which copy of firmware is active" and "Mount the kernel boot partition" then do a directory listing for the /boot directory? That way we can see if the new kernel is actually loaded onto the boot partition.

Perhaps for some reason the new kernel didn't get copied in there properly.

Good luck!

**Comment by switit** [comment]
This work. I got misled to think I could have achieved this with make_seagate_firmware.sh based on this:
https://github.com/bertofurth/Seagate-Central-Samba/blob/main/README_FIRMWARE_UPGRADE_METHOD.md
Many thanks

**Comment by bertofurth** [comment]
Oh dear. Please let me know which part of the instructions were not clear so that I can fix it.

All the best!!

Berto.

**Comment by switit** [comment]
Hi Berto,

What I did was I copied the pre-built uImage.v5.14.0-sc (renamed to uImage) to /cross/boot along with the samba related folders (etc, usr, var) in /cross and run make_seagate_firmware.sh. The script went without error and I could use the resultant firmware image to upgrade via the seagate central web interface. The samba part worked but the kernel part didn't as I reported. So I followed the other instruction suggested by you. I mounted the current kernel (/dev/sda1 in my case) to /boot on seagate central machine and moved the new uImage there and then reboot. This works.

$ testparm -V -> Version 4.14.6

$ uname -a -> Linux Seagate-xxxxxx 5.14.0-sc #1 SMP Fri Sep 10 09:49:35 AEST 2021 armv6l GNU/Linux

But $ ls -al -> lrwxrwxrwx  1 root root   50 Mar  4 13:17 uImage -> uImage-2.6.35.13-cavm1.whitney-econa.whitney-econa

It seemed to me that the make_seagate_firmware.sh could not replace the uImage which resided in /dev/sda1 of the seagate central machine.

Regards,
Witit

**Comment by bertofurth** [comment]
Hi Witit,

I updated the instructions slightly so that after backing up the original kernel, we then delete the original kernel then copy the new one into place.
 
So...
`cp /boot/uImage /boot/uImage.old
rm -f /boot/uImage
cp uImage /boot/uImage`
Hopefully that will fix the issue.

I'm not sure why the firmware upgrade script method didn't overwrite the kernel. When you apply the step under "Copy the new kernel into place" while making the new firmware image it should take the new kernel image and it should replace the original one in the firmware image.
